### ISSUE TITLE
github folder commit

### ISSUE THREAD

**Issue by awkale** [brooklyn-symphony-orchestra/old-bso-wp-site#2]
This folder won't commit then it won't let me sync previous commits. Ever experience this?

This is the error message:
# On branch master
# Your branch is ahead of 'origin/master' by 3 commits.
# 
# Changes not staged for commit:
# (use "git add <file>..." to update what will be committed)
# (use "git checkout -- <file>..." to discard changes in working directory)
# (commit or discard the untracked or modified content in submodules)
# 
# modified:   wp-content/themes/wordpress-bootstrap (modified content, untracked content)
# 

no changes added to commit (use "git add" and/or "git commit -a")
 (256)

Here is a screenshot

www.brooklynsymphonyorchestra.org/images/git-issue.png

**Comment by tim-evans** [comment]
When it says 'dirty' on the sub project, it means you've made changes to the repository, but haven't committed them. Wordpress-bootstrap should probably be a copy instead of a submodule, since it will be edited heavily for the site.

I've also taken a look through the site, and found a few things that would improve formatting specific posts (ie. concerts, rehearsal dates). We can stylize these types by making custom post types in WordPress and then we can represent the data in a consistent fashion.

**Comment by tim-evans** [comment]
FYI- here's some of the docs for custom post types: http://codex.wordpress.org/Post_Types

This is definitely something I can help with, by the by :)

**Comment by awkale** [comment]
Maybe we should meet this weekend. I was just entering content to start working with it. I open to suggestions if you have ideas. I haven't done much besides loading plugins and entering text. 

Alex

**Comment by tim-evans** [comment]
Okay, I get back from vacation Saturday night, so I'd be up for meeting on Sunday. Maybe I can take a peek into how to make custom post types so maybe we can do a spike on getting some simple type working (I'm thinking concerts).

**Comment by awkale** [comment]
Meeting Sunday is fine or during the week. I'm available whenever.

Alex

**Comment by tim-evans** [comment]
How about early afternoon tomorrow? 2-3ish works best for me.

**Comment by awkale** [comment]
Sure 2:30 or 3 is good

**Comment by tim-evans** [comment]
Okay, see you then.
